/* subject_additional_monitoring */
create or replace FUNCTION GET_GEN_SUB_MONT_FN RETURN SYS_REFCURSOR AS
/* subject additional monitoring */
P_VALUE SYS_REFCURSOR;
BEGIN
    OPEN P_VALUE FOR SELECT T_LANG2_NAME GEN_DESC, nvl(T_DRUG_USE,'N/A') DRUG_USE, T_GEN_CODE GEN_CODE FROM T30004 WHERE T_CONTROL_DRUG='1';
    RETURN P_VALUE;
END;
/*
select GET_GEN_SUB_MONT_FN from dual;
*/
/* Result */
/*
{<GEN_DESC=BUTROPIUM BROMIDE,DRUG_USE=60 Days -Two Months,GEN_CODE=1143>,<GEN_DESC=CALAMINE+ZINC OXIDE+GLYCERINE  &amp;amp; WATER,DRUG_USE=1 time,GEN_CODE=1146>,<GEN_DESC=BUDESONIDE,DRUG_USE=9 -Nine Days,GEN_CODE=1286>,<GEN_DESC=DINOPROSTONE,DRUG_USE=N/A,GEN_CODE=1326>,<GEN_DESC=SNAKE ANTIVENOM,DRUG_USE=60 Days -Two Months,GEN_CODE=2169>,<GEN_DESC=ALVERINE CITRATE,DRUG_USE=30 Days -One Month,GEN_CODE=1025>,<GEN_DESC=PHENOBARBITAL,DRUG_USE=N/A,GEN_CODE=1800>,<GEN_DESC=IRBESARTAN,DRUG_USE=5 -Five Days,GEN_CODE=1820>,<GEN_DESC=CODEINE/ACETONAMINOPHIN,DRUG_USE=N/A,GEN_CODE=2686>,<GEN_DESC=ETOPOSIDE,DRUG_USE=1 time,GEN_CODE=1386>,<GEN_DESC=TEST,DRUG_USE=3 -Three Days ,GEN_CODE=3823>,<GEN_DESC=TEST,DRUG_USE=1 time,GEN_CODE=3824>,<GEN_DESC=TEST  1,DRUG_USE=3 -Three Days ,GEN_CODE=3825>,<GEN_DESC=FATEMA CORPORATION,DRUG_USE=9 -Nine Days,GEN_CODE=3828>,<GEN_DESC=TEST2,DRUG_USE=2 -Two Days,GEN_CODE=3829>,<GEN_DESC=TEST,DRUG_USE=N/A,GEN_CODE=3830>,<GEN_DESC=test,DRUG_USE=N/A,GEN_CODE=3839>,<GEN_DESC=TEST 2,DRUG_USE=N/A,GEN_CODE=3840>,<GEN_DESC=SADIKUR RAHKAMN,DRUG_USE=N/A,GEN_CODE=3837>,<GEN_DESC=SAD,DRUG_USE=N/A,GEN_CODE=3838>,<GEN_DESC=IN-PHARMACY PREPARATIONS,DRUG_USE=N/A,GEN_CODE=3841>,<GEN_DESC=FATEMA CORPORATION,DRUG_USE=N/A,GEN_CODE=3842>,<GEN_DESC=QWERTY,DRUG_USE=N/A,GEN_CODE=3843>,}
*/
